from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy.orm import Session
from typing import List

from app.services import service
from app.schemas.invoice import InvoiceSchema
from app.db.database import get_db  # Assuming you have a get_db dependency to yield db sessions

router = APIRouter(
    prefix="/invoices",
    tags=["Invoices"]
)

@router.get("/", response_model=List[InvoiceSchema])
def read_invoices(skip: int = 0, limit: int = 100, db: Session = Depends(get_db)):
    invoices = service.get_invoices(db, skip=skip, limit=limit)
    return invoices

@router.post("/", response_model=InvoiceSchema)
def create_invoice(invoice: InvoiceSchema, db: Session = Depends(get_db)):
    # Check if the invoice ID (generated by frontend) already exists
    db_invoice = service.get_invoice_by_id(db, invoice_id=invoice.id)
    if db_invoice:
        raise HTTPException(status_code=400, detail="Invoice ID already exists")
    
    return service.create_invoice(db=db, invoice_data=invoice)